import localFont from "next/font/local";
import "./globals.css";
import SideNav from "@/components/SideNav";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className='flex w-[100vw] h-[100vh]' >
        <SideNav/>
        <div className="flex text-richblack-5 py-8 px-10 flex-1 bg-richblack-900" >{children}</div>
      </div>
        
      </body>
    </html>
  );
}
